application: firenomics
version: 1
api_version: 1
runtime: python

handlers:
- url: /favicon.png
  static_files: static/favicon.png
  upload: static/favicon.png
- url: /googlehostedservice.html
  static_files: static/googlehostedservice.html
  upload: static/googlehostedservice.html
- url: /rocket/.*
  script: rocket/rocket.py
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /static
  static_dir: static
- url: /admin.*
  script: admin.py
  login: admin
- url: /comment
  script: comments.py
- url: .*
  script: master.py
